import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import { Geist, Geist_Mono } from "next/font/google";
import Header from './components/Header';
import Footer from './components/Footer';
import { Providers } from './providers';

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

//export const metadata: Metadata = {
//  title: "Create Next App",
//  description: "Generated by create next app",
//};

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`flex flex-col min-h-screen bg-[#e0e5ec] dark:bg-[#1a202c] ${geistSans.variable} ${geistMono.variable} antialiased`} >
        <Providers>
          <Header />
            <main className="flex-grow container mx-auto px-4 sm:px-6 lg:px-8 flex items-center justify-center">{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
