version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    container_name: nextjs-app
    command: npm run dev

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8545:8545"
    volumes:
      - ./backend:/app
      - /app/node_modules
    container_name: hardhat-node
    command: npx hardhat node